### ISSUE TITLE
Get an error in ffmpeg_audio() func when adding --mdx_device cuda:1

### ISSUE THREAD

**Issue by xueli12** [Purfview/whisper-standalone-win#398]
Why do I get an error when I add --mdx_device cuda:1, but it works fine without it?

Faster Whisper execution command:

```
./Faster-Whisper-XXL/Faster-Whisper-XXL/faster-whisper-xxl -m large-v2-japanese-5k-steps --model_dir models --verbose true videos/4106665-2.wav -l ja -d cuda:1 --output_format srt --skip -o /working/subtitles --vad_filter true --vad_threshold 0.22 --vad_method silero_v4_fw --ff_mdx_kim2 --one_word 0 --sentence --max_line_width 18 --max_line_count 1 --max_comma 5 --max_comma_cent 50 --vad_device cuda:1 --mdx_device cuda:1

2025-02-07 15:18:35,817 - INFO - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Output: Standalone Faster-Whisper-XXL r245.2 running on: CUDA
2025-02-07 15:18:35,817 - INFO - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Output: Standalone Faster-Whisper-XXL r245.2 running on: CUDA
2025-02-07 15:18:35,819 - INFO - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Output: Number of visible GPU devices: 2
2025-02-07 15:18:35,819 - INFO - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Output: Number of visible GPU devices: 2
2025-02-07 15:18:35,822 - INFO - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Output: Supported compute types by GPU: {'int8', 'float32', 'int8_float16', 'int8_float32', 'float16'}
2025-02-07 15:18:35,822 - INFO - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Output: Supported compute types by GPU: {'int8', 'float32', 'int8_float16', 'int8_float32', 'float16'}
2025-02-07 15:18:35,824 - INFO - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Output: Audio filtering is in progress...
2025-02-07 15:18:35,824 - INFO - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Output: Audio filtering is in progress...
2025-02-07 15:18:35,852 - ERROR - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Error: Error: Some error in ffmpeg_audio() func.
2025-02-07 15:18:35,852 - ERROR - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Error: Error: Some error in ffmpeg_audio() func.
2025-02-07 15:18:36,228 - INFO - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Faster Whisper return value: 130
2025-02-07 15:18:36,228 - INFO - [Task 1] [File videos/[4106665-2.wav](http://4106665-2.wav/)] Faster Whisper return value: 130
```

**Comment by Purfview** [comment]
What is "cuda:1" device and why you use it?
Why there is everything repeated twice in console?

**Comment by xueli12** [comment]
> What is "cuda:1" device and why you use it? Why there is everything repeated twice in console?

What puzzles me is that using these parameters together results in an error:
-d cuda:1 --vad_method silero_v4_fw --vad_device cuda:1 --ff_mdx_kim2 --mdx_device cuda:1
However, it runs fine without --mdx_device cuda:1, i.e., with:
-d cuda:1 --vad_method silero_v4_fw --vad_device cuda:1 --ff_mdx_kim2

**Comment by Purfview** [comment]
>The reason for using it is to leverage multithreading to fully utilize both GPUs and make them work simultaneously.

And how you do that?

>--vad_method silero_v4_fw --vad_device cuda:1

Silero is cpu only.

>What puzzles me is that using these parameters together results in an error:
-d cuda:1 --vad_method silero_v4_fw --vad_device cuda:1 --ff_mdx_kim2 --mdx_device cuda:1

Probably a bug. That's on kaggle? How much RAM it offers for free?

**Comment by xueli12** [comment]
> > The reason for using it is to leverage multithreading to fully utilize both GPUs and make them work simultaneously.
> 
> And how you do that?
> 
> > --vad_method silero_v4_fw --vad_device cuda:1
> 
> Silero is cpu only.
> 
> > What puzzles me is that using these parameters together results in an error:
> > -d cuda:1 --vad_method silero_v4_fw --vad_device cuda:1 --ff_mdx_kim2 --mdx_device cuda:1
> 
> Probably a bug. That's on kaggle? How much RAM it offers for free?


Yes, 30GB

**Comment by xueli12** [comment]
> > The reason for using it is to leverage multithreading to fully utilize both GPUs and make them work simultaneously.
> 
> And how you do that?
> 
> > --vad_method silero_v4_fw --vad_device cuda:1
> 
> Silero is cpu only.
> 
> > What puzzles me is that using these parameters together results in an error:
> > -d cuda:1 --vad_method silero_v4_fw --vad_device cuda:1 --ff_mdx_kim2 --mdx_device cuda:1
> 
> Probably a bug. That's on kaggle? How much RAM it offers for free?

Thank you for pointing out the error. By the way, does adding the parameter --vad_device cuda:1 have any impact?

**Comment by Purfview** [comment]
I'll test it in kaggle to see what's up with "--mdx_device cuda:1".
As both GPU devices there are same then there's no point to set it to the second one.

>By the way, does adding the parameter --vad_device cuda:1 have any impact?

It has no effect with silero.

**Comment by Purfview** [comment]
Fixed in r245.3

**Comment by xueli12** [comment]
> Fixed in r245.3

r245.4 linux
I still encountered an error when using --voc_device cuda:1, but there was no issue when using --voc_device cuda: 
Loading model...
[Task 1] [File videos/222.wav] Starting processing file
[Task 1] [File videos/222.wav] Using device: cuda:1
[Task 1] [File videos/222.wav] Transcribing in progress...
[Task 1] [File videos/222.wav] Faster Whisper command: ./Faster-Whisper-XXL/Faster-Whisper-XXL/faster-whisper-xxl -m large-v2-japanese-5k-steps --model_dir models --print_progress videos/222.wav -l ja -d cuda:1 --output_format srt --skip -o /kaggle/working/subtitles --vad_filter true --vad_threshold 0.22 --vad_method pyannote_v3 --vad_device cuda:1 --one_word 0 --sentence --max_line_width 18 --max_line_count 1 --max_comma 5 --max_comma_cent 50 --ff_vocal_extract mdx_kim2 --voc_device cuda:1
2025-07-04 17:54:10,274 - INFO - [Task 1] [File videos/222.wav] Output: Standalone Faster-Whisper-XXL r245.4 running on: CUDA
2025-07-04 17:54:10,278 - INFO - [Task 1] [File videos/222.wav] Output: Starting to process: videos/222.wav
2025-07-04 17:54:10,284 - INFO - [Task 1] [File videos/222.wav] Output: Audio filtering is in progress...
2025-07-04 17:54:10,308 - INFO - [Task 1] [File videos/222.wav] Output: Traceback (most recent call last):
2025-07-04 17:54:10,312 - INFO - [Task 1] [File videos/222.wav] Output: File "__main__.py", line 176, in ffmpeg_audio
2025-07-04 17:54:10,312 - INFO - [Task 1] [File videos/222.wav] Output: File "__main__.py", line 176, in ffmpeg_audio
2025-07-04 17:54:10,316 - INFO - [Task 1] [File videos/222.wav] Output: File "faster_whisper/mdx_infer.py", line 117, in __init__
2025-07-04 17:54:10,319 - ERROR - [Task 1] [File videos/222.wav] Error: NameError: name 'device' is not defined
2025-07-04 17:54:10,644 - INFO - [Task 1] [File videos/222.wav] Faster Whisper returned code: 130

**Comment by Purfview** [comment]
But it should have been fixed in r245.3... maybe it regressed in r245.4!?

I'll check it again.

**Comment by Purfview** [comment]
Do you run two tasks at the same time there?

**Comment by xueli12** [comment]
> Do you run two tasks at the same time there?

I've tried running it both separately and simultaneously — the result is the same.

**Comment by Purfview** [comment]
Should be fixed in Pro r3.256.1 [not tested]. Report if it still doesn't work.
